### ISSUE TITLE
Configuration and AccessList Controllers

### ISSUE THREAD

**Issue by AdriVig** [Grenadingue/spatch#12]
- spatch configuration
  - [x] configuration control
    - [x] read configuration file
      - [x] read server configuration
      - [x] read user list
      - [x] read user access right list
      - [x] read user control list
      - [x] read endpoint list
    - [x] set server configuration
    - [x] set user list
    - [x] set user access right list
    - [x] set user control list
    - [x] set endpoint list
  - [x] access control list
    - [x] use configuration datas
    - [x] use server configuration
    - [x] use user list
    - [x] use user access right list
    - [x] use endpoint list

**Comment by Grenadingue** [comment]
Sample server configuration file
```
[server]
port=42042

[local_users]
# username=password
toto=toto
foo=foo
baz=baz
root=root

[endpoints]
# endpoint_name=ip_address|port
endpoint1=10.0.2.15|22
endpoint2=10.0.2.16|22
endpoint3=10.0.2.17|22

[users_control]
# local_username=available_endpoint_1|available_endpoint_2|...
toto=endpoint1|endpoint2
foo=endpoint3|
baz=
root=endpoint1|endpoint2|endpoint3

[remote_users]
# local_username|endpoint_name=available_username_1|available_username_2|...
toto|endpoint1=toto|root
toto|endpoint2=root
foo|endpoint3=foo|root
root|endpoint1=root
root|endpoint2=root
root|endpoint3=root
```

**Comment by Grenadingue** [comment]
cf. #4 Project's to do tree
